routes/web.php
<?php
Route::group( ['domain' => 'www.'.config('app.baseURL')], function(){
	Route::get('/', function() {
    	//TODO: redirect this to the main domain + the slug that came in -- somehow :/
	    return redirect(config('app.baseURL'));
	});

	Route::get('/{slug}/{slug2}', function($slug, $slug2) {
    	//TODO: redirect this to the main domain + the slug that came in -- somehow :/
	    return redirect(config('app.baseURL').'/'.$slug.'/'.$slug2);
	});

	Route::get('/blog', function() {
    	//TODO: redirect this to the main domain + the slug that came in -- somehow :/
	    return redirect(config('app.baseURL').'/blog');
	});
});
// Atölye Routerları (atolye.dugunatolyeleri.com)
// Controller dizini (app/Http/Controllers/Workshop/..)
Route::group( ['domain' => 'atolye.'.config('app.baseURL'), 'namespace' => 'Workshop'], function(){

	Route::group( [ 'middleware' => 'workshop' ],function(){

		Route::get('/', 'HomeController@getIndex')->name('workshop.dashboard');
		// Genel Bilgiler
		Route::get('panel', 'GeneralsController@getIndex')->name('workshop.panel');
		Route::put('panel', 'GeneralsController@postGeneralUpdate')->name('workshop.panel.update.post');
		Route::put('atolye-gorseli', 'GeneralsController@postImageUpdate')->name('workshop.image.update.post');
		Route::put('atolye-detay', 'GeneralsController@postDetailUpdate')->name('workshop.detail.update.post');
		Route::put('sorular', 'GeneralsController@postQuestionsUpdate')->name('workshop.questions.update.post');
		// Paket Sayfası
		Route::get('packages', 'PaymentsController@getPackages')->name('get.packages');
		// Paket fiyatlarının post edildiği sayfa
		Route::post('packages', 'PaymentsController@postPackages')->name('post.packages');
		// Premium info
		Route::get('premium', 'PremiumController@getIndex')->name('get.premium');
		// Fatura işlemleri
		Route::get('bill', 'PaymentsController@getBill')->name('get.bill');
		Route::post('bill', 'PaymentsController@postBill')->name('post.bill');
		// Ödeme sayfası
		Route::get('card', 'PaymentsController@getCardForm')->name('get.card.form');
		Route::post('card', 'PaymentsController@postCard')->name('post.card');
		// Ödeme geri dönüş sayfası
		Route::post('completed', 'PaymentsController@getSubscribeSuccess')->name('subscribe.success');
		// Testinh
		Route::get('demo', 'PaymentsController@foo');
		// Route::post('demo', 'PaymentsController')->name('')
		
		// Galeri
		Route::get('galeri', 'GalleryController@getIndex')->name('workshop.gallery');
		Route::post('galeri', 'GalleryController@postUpdate')->name('workshop.gallery.update.post');
		Route::post('image/destroy/{id}', 'GalleryController@imageDestroy')->name('gallery.image.destroy');
		Route::post('image/sortable', 'GalleryController@imageSortable')->name('workshop.image.sortable');
		Route::post('image/conf/{id}', 'GalleryController@imageConf');
		Route::post('image/detail', 'GalleryController@postImageDetail')->name('workshop.image.detail');
		// Video Galeri
		// Route::get('video', 'VideosController@getIndex')->name('workshop.video');
		// Route::put('video', 'VideosController@postUpdate')->name('workshop.video.post');
		Route::resource('videos', 'VideosController');
		// Teklifler
		Route::get('teklifler', 'OffersController@getIndex')->name('workshop.offers');
		Route::post('offer/addcontract', 'OffersController@addContract')->name('workshop.offer.add');
		Route::post('offer/destroyContract', 'OffersController@destroyContract')->name('workshop.offer.destroy');
		// Yorumlar
		Route::get('yorumlar', 'CommentsController@getIndex')->name('workshop.comments');
		Route::delete('comment/{id}', 'CommentsController@destroyOffer')->name('workshop.comment.destroy');
		Route::post('comment/confirm/{id}', 'CommentsController@confirmComment')->name('workshop.comment.confirm');
		Route::post('comment/disabled/{id}', 'CommentsController@disabledComment')->name('workshop.comment.disabled');
		// Kampanyalar
		Route::resource('campaigns', 'CampaignsController');
		// İstatistikler
		Route::get('istatistikler', 'AnalyticsController@getIndex')->name('workshop.analytics');
		// Kişiler
		Route::get('kisileri-yonet', 'PersonsController@getIndex')->name('workshop.persons');
		// Ödeme işlemleri
		Route::get('odeme', 'PaymentsController@getIndex')->name('workshop.payment');
		// Çıkış Yap
		Route::get('cikis', 'AuthController@getLogout')->name('workshop.logout');

	});

	// Atöyle Giriş Routerları

	Route::get('giris', 'AuthController@getLogin')->name('workshop.login');
	Route::post('giris', 'AuthController@postLogin')->name('workshop.login.post');

	//  Atölye Kayıt Routerları

	Route::get('/kayit', 'AuthController@getRegister')->name('workshop.register');
	Route::post('/kayit', 'AuthController@postRegister')->name('workshop.register.post');

});

// Kullanıcı Routerları (kullanici.dugunatolyeleri.com)
// Controller dizini (app/Http/Controllers/User/..)

Route::group( ['domain' => 'kullanici.'.config('app.baseURL'), 'namespace' => 'User'], function(){

	Route::group( ['middleware' => 'auth'],function(){

		Route::get('/', 'HomeController@getIndex')->name('user.dashboard');
		Route::put('/user/{id}', 'UserController@postUpdate')->name('user.update.post');
		Route::get('tekliflerim', 'OffersController@getOffers')->name('user.offers');
		Route::get('listelerim', 'ListsController@getLists')->name('user.lists');
		Route::get('favorilerim', 'FavoritesController@getFavorites')->name('user.favorites');
		Route::post('user/favorites', 'FavoritesController@addFavorite')->name('add.user.favorite');
		Route::get('yorumlarim', 'CommentsController@getComments')->name('user.comments');
		Route::delete('comment/destroy/{id}', 'CommentsController@commentDestroy')->name('user.comment.destroy');
		Route::get('ayarlarim', 'HomeController@getIndex')->name('user.settings');
		// Kullanıcı Atölye Beğenme
		// Kullanıcı Oturum Sonlandırma
		Route::get('logout', 'AuthController@getLogout')->name('user.logout');

	});



		// Kullanıcı Giriş Routerları
		Route::get('giris', 'AuthController@getLogin')->name('user.login');
		Route::post('giris', 'AuthController@postLogin')->name('user.login.post');
		// Facebook ile giriş
		Route::get('facebook/login', 'AuthController@getFacebookLogin')->name('get.facebook.login');
		Route::get('facebook/login/callback', 'AuthController@handleProviderCallback')->name('redirect.facebook.login');

		//  Kullanıcı Kayıt Routerları
		Route::get('kayit', 'AuthController@getRegister')->name('user.register');
		Route::post('kayit', 'AuthController@postRegister')->name('user.register.post');
		Route::get('register/activation/{token}', 'AuthController@confirmation')->name('user.activation');

		// Şifre sıfırlama
		Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('get.password.reset');
		Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('post.password.reset');
		Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('get.password.token');
		Route::post('password/reset', 'ResetPasswordController@reset')->name('post.password');

	
});
// Admin Paneli Routerları (admin.dugunatolyeleri.com)
// Controller dizini (app/Http/Controllers/Admin/..)

Route::group( ['domain' => 'admin.'.config('app.baseURL'), 'namespace' => 'Admin'], function(){	
	Route::group([ 'middleware' => 'admin'], function(){
		// Backup Route
		Route::get('getBackup', 'BackupController@getBackup')->name('get.backup');

		Route::get('workshopfoo', 'HomeController@getFoo');

		Route::get('/', 'HomeController@getIndex')->name('admin.dashboard');
		Route::post('workshopbycateogory', 'HomeController@postWorkshopByCategory')->name('workshopByCategory');
		// Site Ayarları
		Route::get('/settings', 'SettingController@getIndex')->name('get.settings');
		Route::post('/settings', 'SettingController@postUpdate')->name('post.setting');
		// Slider Yönetimi
		Route::resource('sliders', 'SliderController');
		// Kategoriler
		Route::resource('categories', 'CategoryController');
		Route::post('categorie/sortable', 'CategoryController@postSortable')->name('categorie.sortable');
		// Admins
		Route::resource('admins', 'AdminController');
		// Atöylyeler
		Route::resource('workshops', 'WorkshopController');
		Route::get('/workshop-list', 'WorkshopController@getData')->name('workshops.data');
		Route::get('workshop/disabled', 'WorkshopController@getDisabledWorkshops')->name('disabled.workshops');
		Route::get('workshop/disabled/list', 'WorkshopController@getDisabledData')->name('disabled.workshops.data');
		Route::get('workshop/waiting/list', 'WorkshopController@getWaitingData')->name('waiting.workshops.data');
		Route::post('image/destroy/{id}', 'WorkshopController@imageDestroy');
		Route::post('image/conf/{id}', 'WorkshopController@imageConf');
		Route::post('image/sortable', 'WorkshopController@imageSortable')->name('image.sortable');
		Route::put('create/acc/{id}', 'WorkshopController@createAcc')->name('create.acc');

		Route::post('questions/{id}', 'WorkshopController@postQuestions')->name('post.questions');
		Route::put('images/{id}', 'WorkshopController@postImages')->name('post.images');
		Route::put('details/{id}', 'WorkshopController@postWorkshopDetail')->name('post.details');
		Route::put('gallery/{id}', 'WorkshopController@postGallery')->name('post.gallery');
		Route::put('video/{id}', 'WorkshopController@postVideo')->name('post.video');
		Route::put('other/{id}', 'WorkshopController@postOther')->name('post.other');
		// Teklifler
		Route::resource('offers', 'OfferController');
		// Üyeler
		Route::resource('users', 'UserController');
		// Panel Kullanıcıları
		Route::resource('admins', 'AdminController');
		// Blog
		Route::resource('blogs', 'BlogController');
		Route::post('blog-image-destroy', 'BlogController@imageDestroy')->name('blog.image.destroy');
		Route::resource('blog-categories', 'BlogCategoryController');

app/Http/Controllers/Admin/BlogController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Blog;
use App\Models\BlogCategory as Category;
use App\Models\BlogGallery as Gallery;
use Intervention\Image\ImageManagerStatic as Image;
use App\Models\BlogComment as Comment;
use Auth;

class BlogController extends Controller
{

    protected $viewPath = '_admin.pages.blogs.';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Blog::orderBy('created_at', 'DESC')->get();
        return view($this->viewPath.'list', compact('items', 'categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::pluck('title', 'id');
        return view($this->viewPath.'create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $table = new Blog;
        $table->cover = $request->cover;
        $table->blog_category_id = $request->category;
        $table->title = $request->title;
        $table->slug = str_slug($request->title);
        $table->description = $request->description;
        $table->content = $request->content;
        $table->active = $request->active;
        $table->save();
        if($request->imageCheck){
            if($request->hasFile('images')){
                foreach($request->images as $image):
                    $file = public_path('uploads/blog/');
                    \File::exists($file) or \File::makeDirectory($file);
                    $fileName = time().rand().'.'.$image->getClientOriginalExtension();
                    $blogFile = Image::make($image->getRealPath());
                    $blogFile->resize(500, null, function($constraint){
                        $constraint->aspectRatio();
                    })->save($file . $fileName);

                    $model = new Gallery;
                    $model->blog_id = $table->id;
                    $model->filename = $fileName;
                    $model->save();
                endforeach;
            }
        }
        return redirect(route('blogs.edit', $table->id))->with('message', 'Blog başarıyla eklendi');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Blog::findOrFail($id);
        $categories = Category::pluck('title', 'id');
        return view($this->viewPath.'update', compact('item', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $table = Blog::findOrFail($id);
        $table->cover = $request->cover;
        $table->blog_category_id = $request->category;
        $table->title = $request->title;
        $table->slug = str_slug($request->title);
        $table->description = $request->description;
        $table->content = $request->content;
        $table->active = $request->active;
        $table->save();
        if($request->imageCheck){
            if($request->images){
                foreach($request->images as $image):
                    $file = public_path('uploads/blog/');
                    \File::exists($file) or \File::makeDirectory($file);
                    $fileName = time().rand().'.'.$image->getClientOriginalExtension();
                    $blogFile = Image::make($image->getRealPath());
                    $blogFile->resize(500, null, function($constraint){
                        $constraint->aspectRatio();
                    })->save($file . $fileName);

                    $model = new Gallery;
                    $model->blog_id = $table->id;
                    $model->filename = $fileName;
                    $model->save();
                endforeach;
            }
        }
        return back()->with('message', 'Blog başarıyla düzenlendi');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $workshop = Blog::findOrFail($id);
        $workshop->delete();
        sleep(1);
        return back();
    }

    public function imageDestroy(Request $request)
    {
        if($request->ajax())
        {
            $table = Gallery::findOrFail($request->id);
            $table->delete();
            return response()->json([ 'success' => true ]);
        }
    }
}

app/Http/Controllers/Admin/CommentsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Comment;

class CommentsController extends Controller
{
    protected $viewPath = "_admin.pages.comments.";
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Comment::whereActive('0')->get();
        return view($this->viewPath.'list', compact('items'));  
    }

    public function getActive($id)
    {
        $item = Comment::findOrFail($id);
        $item->active = $item->active == 1 ? 0 : 1;
        $item->save();
        \Session::flash('message', 'Yorum düzenleme işlemi başarılı');
        return back();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Comment::findOrFail($id);
        return view($this->viewPath.'update', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $table = Comment::findOrFail($id);
        $table->female = $request->female;
        $table->male = $request->male;
        $table->title = $request->title;
        $table->active = $request->active;
        $table->content = $request->content;
        $table->save();
        \Session::flash('message', 'Yorum başarıyla düzenlendi!');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Comment::findOrFail($id);
        $item->delete();
        sleep(1);
        return back();
    }

    public function getActiveComments()
    {
        $items = Comment::whereActive('1')->get();
        return view($this->viewPath.'list', compact('items'));
    }
}

resources/views/_admin/pages/blogs/comments/create.blade.php
@extends('_admin.master')
@section('content')
<div class="main-content">
    <div class="panel-content">
        <div class="row">
            <div class="col-md-12">
                <div class="heading-sec">
                    <div class="row">
                        <div class="col-md-12">
                            @include('_admin.layouts.notifications')
                        </div>
                    </div>
                </div>
                <div class="widget">
                 <div class="form-elements-sec">
                    <div class="widget-title">
                        <h3>Slider Ekle</h3>
                    </div>
                    {!! Form::open([ 'url' => route('sliders.store'), 'class' => 'sec', 'role' => 'form' ]) !!}
                    <div class="row">
                        <div class="col-md-12 mb">
                            <div class="input-group">
                                <span class="input-group-btn">
                                    <a id="cover" data-input="cover_picture" data-preview="cover_preview" class="btn btn-edit" style="height: 45px;">
                                        <i class="fa fa-picture-o" style="vertical-align: -webkit-baseline-middle;"></i> 
                                    </a>
                                </span>
                                <input id="cover_picture" class="form-control custom-input" type="text" name="image" placeholder="Kapak Resmi">
                            </div>
                            <img id="cover_preview" style="margin-top:15px;max-height:100px;">
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-6 m-b">
                            <div class="form-group">
                                <input type="text" placeholder="Başlık" class="form-control custom-input" name="title">
                            </div>
                        </div>
                        <div class="col-md-6 m-b">
                            <div class="form-group">
                                <input type="text" placeholder="Buton Yazısı" class="form-control custom-input" name="button_text">
                            </div>
                        </div>
                        <div class="col-md-6 m-b">
                            <div class="form-group">
                                <input type="text" class="form-control custom-input" name="url" placeholder="Link">
                            </div>
                        </div>
                        <div class="col-md-6 m-b">
                            <div class="form-group">
                                <select name="active" id="access" class="form-control custom-input" placeholder="Seçiniz">
                                    <option value="" disabled selected hidden>Durum</option>
                                    <option value="1">Aktif</option>
                                    <option value="0">Pasif</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <textarea name="description" id=""  rows="5" class="form-control custom-input" placeholder="Açıklama"></textarea>
                            </div>
                        </div>
                        <hr>
                        <div class="col-md-12">
                            <div class="record-buttons">
                                <button class="btn btn-edit" type="submit">
                                    <i class="fa fa-plus"></i> Slider Ekle
                                </button>
                                <a href="{{ route('sliders.index') }}">
                                    <button class="btn btn-trash" type="button">
                                        <i class="fa fa-remove"></i> İptal
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div><!-- Panel Content -->
</div><!-- Main Content -->
@endsection
@push('script')
<script>

</script>
@endpush

resources/views/_admin/pages/blogs/comments/list.blade.php
@extends('_admin.master')
@section('content')
<div class="main-content">
    <div class="panel-content">
        <div class="row">
            <div class="col-md-12">
                <div class="heading-sec">
                    <div class="row">
                        <div class="col-md-12">
                            @include('_admin.layouts.notifications')
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="heading-sec">
        <div class="mini-stats-sec">
            <div class="row">
                <a href="{{ route('get.active.blog.comments') }}">
                    <div class="col-md-4 pull-right">
                        <div class="widget">
                            <div class="mini-stats">
                                <span class="red-skin"><i class="fa fa-check"></i></span>
                                <h3>Yorumlar</h3>
                                <p>Onaylanmış Yorumlar Listesi</p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div><!-- Mini stats Sec -->
    </div><!-- Top Bar Chart -->
        <div class="row">
            <div class="col-md-12">
                <div class="widget">
                    <div class="table-area">
                        <div class="widget-title">
                            <h3>Yorum Tablosu</h3>
                            <span>{{count($items)}} Yorum Listelendi</span>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Yorum</th>
                                        <th>Blog</th>
                                        <th>Tarih</th>
                                        <th>İşlemler</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @forelse($items as $item)
                                    <tr>
                                        <td>{{ $item->title }}</td>
                                        <td>{{ $item->blog->title }}</td>
                                        <td>{{ $item->created_at->diffForHumans() }}</td>
                                        <td>
                                            <a href="{{route('blog-comments.active', $item->id)}}">
                                                <button class="btn btn-warning">
                                                    {{ $item->active == 1 ? 'Yayından Al' : 'Onayla' }}
                                                    <i class="fa {{{ $item->active == 1 ? 'fa-eye-slash' : 'fa-check' }}}"></i>
                                                </button>
                                            </a>
                                            <a href="{{route('blog-comments.edit', $item->id)}}">
                                                <button class="btn btn-edit">
                                                    Düzenle <i class="fa fa-edit"></i>
                                                </button>
                                            </a>
                                            {!! stuff_destroy([ 'blog-comments.destroy', $item->id]) !!}
                                        </td>
                                    </tr>
                                @empty
                                    <h3 class="text-center" style="color: #ff6b6b"> <i class="fa fa-exclamation" aria-hidden="true"></i> Yorum Bulunamadı</h3>
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- Panel Content -->
</div><!-- Main Content -->
@endsection

resources/views/_admin/pages/blogs/comments/update.blade.php
@extends('_admin.master')
@section('content')
<div class="main-content">
    <div class="panel-content">
        <div class="row">
            <div class="col-md-12">
                <div class="heading-sec">
                    <div class="row">
                        <div class="col-md-12">
                            @include('_admin.layouts.notifications')
                        </div>
                    </div>
                </div>
                <div class="widget">
                 <div class="form-elements-sec">
                    <div class="widget-title">
                        <h3>Yorum Düzenle</h3>
                    </div>
                    {!! Form::open([ 'url' => route('comments.update', $item->id), 'class' => 'sec', 'role' => 'form' ]) !!}
                    {{ method_field('PUT') }}
                    <div class="row">
                        <div class="col-md-6 m-b">
                            <div class="form-group">
                                <label>Gelin</label>
                                <input type="text" value="{{ $item->female }}" placeholder="Başlık" class="form-control custom-input" name="female">
                            </div>
                        </div>
                        <div class="col-md-6 m-b">
                            <div class="form-group">
                                <label>Damat</label>
                                <input type="text" value="{{ $item->male }}" placeholder="Buton Yazısı" class="form-control custom-input" name="male">
                            </div>
                        </div>
                        <div class="col-md-6 m-b">
                            <div class="form-group">
                                <label>Başlık</label>
                                <input type="text" value="{{ $item->title }}" class="form-control custom-input" name="title" placeholder="Başlık">
                            </div>
                        </div>
                        <div class="col-md-6 m-b">
                            <div class="form-group">
                                <label>Durum</label>
                                {!! Form::select('active',
                                    [ '1' => 'Aktif', '0' => 'Pasif' ],
                                    $item->active,
                                    ['class' => 'form-control custom-input']) !!}
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Yorum</label>
                                    <textarea name="content" id=""  rows="5" class="form-control custom-input" placeholder="Açıklama">{{ $item->content }}</textarea>
                                </div>
                            </div>
                            <hr>
                            <div class="col-md-12">
                                <div class="record-buttons">
                                    <button class="btn btn-edit" type="submit">
                                        <i class="fa fa-edit"></i> Yorum Düzenle
                                    </button>
                                    <a href="{{ route('comments.index') }}">
                                        <button class="btn btn-trash" type="button">
                                            <i class="fa fa-remove"></i> İptal
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div><!-- Panel Content -->
</div><!-- Main Content -->
@endsection
@push('script')
<script>

</script>
@endpush