routes/web.php
		Route::get('packages', 'PaymentsController@getPackages')->name('get.packages');
		// Paket fiyatlarının post edildiği sayfa
		Route::post('packages', 'PaymentsController@postPackages')->name('post.packages');
		// Premium info
		Route::get('premium', 'PremiumController@getIndex')->name('get.premium');
		// Fatura işlemleri
		Route::get('bill', 'PaymentsController@getBill')->name('get.bill');
		Route::post('bill', 'PaymentsController@postBill')->name('post.bill');
		// Ödeme sayfası
		Route::get('card', 'PaymentsController@getCardForm')->name('get.card.form');
		Route::post('card', 'PaymentsController@postCard')->name('post.card');
		// Ödeme geri dönüş sayfası
		Route::post('completed', 'PaymentsController@getSubscribeSuccess')->name('subscribe.success');
		// Testinh
		Route::get('demo', 'PaymentsController@foo');
		// Route::post('demo', 'PaymentsController')->name('')
		
		// Galeri
		Route::get('galeri', 'GalleryController@getIndex')->name('workshop.gallery');
		Route::post('galeri', 'GalleryController@postUpdate')->name('workshop.gallery.update.post');
		Route::post('image/destroy/{id}', 'GalleryController@imageDestroy')->name('gallery.image.destroy');
		Route::post('image/sortable', 'GalleryController@imageSortable')->name('workshop.image.sortable');
		Route::post('image/conf/{id}', 'GalleryController@imageConf');
		Route::post('image/detail', 'GalleryController@postImageDetail')->name('workshop.image.detail');
		// Video Galeri
		// Route::get('video', 'VideosController@getIndex')->name('workshop.video');
		// Route::put('video', 'VideosController@postUpdate')->name('workshop.video.post');
		Route::resource('videos', 'VideosController');
		// Teklifler
		Route::get('teklifler', 'OffersController@getIndex')->name('workshop.offers');
		Route::post('offer/addcontract', 'OffersController@addContract')->name('workshop.offer.add');
		Route::post('offer/destroyContract', 'OffersController@destroyContract')->name('workshop.offer.destroy');
		// Yorumlar
		Route::get('yorumlar', 'CommentsController@getIndex')->name('workshop.comments');
		Route::delete('comment/{id}', 'CommentsController@destroyOffer')->name('workshop.comment.destroy');
		Route::post('comment/confirm/{id}', 'CommentsController@confirmComment')->name('workshop.comment.confirm');
		Route::post('comment/disabled/{id}', 'CommentsController@disabledComment')->name('workshop.comment.disabled');
		// Kampanyalar
		Route::resource('campaigns', 'CampaignsController');
		// İstatistikler
		Route::get('istatistikler', 'AnalyticsController@getIndex')->name('workshop.analytics');
		// Kişiler
		Route::get('kisileri-yonet', 'PersonsController@getIndex')->name('workshop.persons');
		// Ödeme işlemleri
		Route::get('odeme', 'PaymentsController@getIndex')->name('workshop.payment');
		// Çıkış Yap
		Route::get('cikis', 'AuthController@getLogout')->name('workshop.logout');

	});

	// Atöyle Giriş Routerları

	Route::get('giris', 'AuthController@getLogin')->name('workshop.login');
	Route::post('giris', 'AuthController@postLogin')->name('workshop.login.post');

	//  Atölye Kayıt Routerları

	Route::get('/kayit', 'AuthController@getRegister')->name('workshop.register');
	Route::post('/kayit', 'AuthController@postRegister')->name('workshop.register.post');

});

// Kullanıcı Routerları (kullanici.dugunatolyeleri.com)
// Controller dizini (app/Http/Controllers/User/..)

Route::group( ['domain' => 'kullanici.'.config('app.baseURL'), 'namespace' => 'User'], function(){

	Route::group( ['middleware' => 'auth'],function(){

		Route::get('/', 'HomeController@getIndex')->name('user.dashboard');
		Route::put('/user/{id}', 'UserController@postUpdate')->name('user.update.post');
		Route::get('tekliflerim', 'OffersController@getOffers')->name('user.offers');
		Route::get('listelerim', 'ListsController@getLists')->name('user.lists');
		Route::get('favorilerim', 'FavoritesController@getFavorites')->name('user.favorites');
		Route::post('user/favorites', 'FavoritesController@addFavorite')->name('add.user.favorite');
		Route::get('yorumlarim', 'CommentsController@getComments')->name('user.comments');
		Route::delete('comment/destroy/{id}', 'CommentsController@commentDestroy')->name('user.comment.destroy');
		Route::get('ayarlarim', 'HomeController@getIndex')->name('user.settings');
		// Kullanıcı Atölye Beğenme
		// Kullanıcı Oturum Sonlandırma
		Route::get('logout', 'AuthController@getLogout')->name('user.logout');

	});



		// Kullanıcı Giriş Routerları
		Route::get('giris', 'AuthController@getLogin')->name('user.login');
		Route::post('giris', 'AuthController@postLogin')->name('user.login.post');
		// Facebook ile giriş
		Route::get('facebook/login', 'AuthController@getFacebookLogin')->name('get.facebook.login');
		Route::get('facebook/login/callback', 'AuthController@handleProviderCallback')->name('redirect.facebook.login');

		//  Kullanıcı Kayıt Routerları
		Route::get('kayit', 'AuthController@getRegister')->name('user.register');
		Route::post('kayit', 'AuthController@postRegister')->name('user.register.post');
		Route::get('register/activation/{token}', 'AuthController@confirmation')->name('user.activation');

		// Şifre sıfırlama
		Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('get.password.reset');
		Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('post.password.reset');
		Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('get.password.token');
		Route::post('password/reset', 'ResetPasswordController@reset')->name('post.password');

	
});
// Admin Paneli Routerları (admin.dugunatolyeleri.com)
// Controller dizini (app/Http/Controllers/Admin/..)

Route::group( ['domain' => 'admin.'.config('app.baseURL'), 'namespace' => 'Admin'], function(){	
	Route::group([ 'middleware' => 'admin'], function(){
		// Backup Route
		Route::get('getBackup', 'BackupController@getBackup')->name('get.backup');

		Route::get('workshopfoo', 'HomeController@getFoo');

		Route::get('/', 'HomeController@getIndex')->name('admin.dashboard');
		Route::post('workshopbycateogory', 'HomeController@postWorkshopByCategory')->name('workshopByCategory');
		// Site Ayarları
		Route::get('/settings', 'SettingController@getIndex')->name('get.settings');
		Route::post('/settings', 'SettingController@postUpdate')->name('post.setting');
		// Slider Yönetimi
		Route::resource('sliders', 'SliderController');
		// Kategoriler
		Route::resource('categories', 'CategoryController');
		Route::post('categorie/sortable', 'CategoryController@postSortable')->name('categorie.sortable');
		// Admins
		Route::resource('admins', 'AdminController');
		// Atöylyeler
		Route::resource('workshops', 'WorkshopController');
		Route::get('/workshop-list', 'WorkshopController@getData')->name('workshops.data');
		Route::get('workshop/disabled', 'WorkshopController@getDisabledWorkshops')->name('disabled.workshops');
		Route::get('workshop/disabled/list', 'WorkshopController@getDisabledData')->name('disabled.workshops.data');
		Route::get('workshop/waiting/list', 'WorkshopController@getWaitingData')->name('waiting.workshops.data');
		Route::post('image/destroy/{id}', 'WorkshopController@imageDestroy');
		Route::post('image/conf/{id}', 'WorkshopController@imageConf');
		Route::post('image/sortable', 'WorkshopController@imageSortable')->name('image.sortable');
		Route::put('create/acc/{id}', 'WorkshopController@createAcc')->name('create.acc');

		Route::post('questions/{id}', 'WorkshopController@postQuestions')->name('post.questions');
		Route::put('images/{id}', 'WorkshopController@postImages')->name('post.images');
		Route::put('details/{id}', 'WorkshopController@postWorkshopDetail')->name('post.details');
		Route::put('gallery/{id}', 'WorkshopController@postGallery')->name('post.gallery');
		Route::put('video/{id}', 'WorkshopController@postVideo')->name('post.video');
		Route::put('other/{id}', 'WorkshopController@postOther')->name('post.other');
		// Teklifler
		Route::resource('offers', 'OfferController');
		// Üyeler
		Route::resource('users', 'UserController');
		// Panel Kullanıcıları
		Route::resource('admins', 'AdminController');
		// Blog
		Route::resource('blogs', 'BlogController');
		Route::post('blog-image-destroy', 'BlogController@imageDestroy')->name('blog.image.destroy');
		Route::resource('blog-categories', 'BlogCategoryController');
		Route::post('blog-categories/sortable', 'BlogCategoryController@postSortable')->name('blog.categorie.sortable');
		Route::resource('blog-comments', 'BlogCommentsController');
		Route::get('blog-comments/active/list', 'BlogCommentsController@getActiveComments')->name('get.active.blog.comments');
		Route::get('blog-comments/active/{id}', 'BlogCommentsController@getActive')->name('blog-comments.active');
		// Yorumlar
		Route::resource('comments', 'CommentsController');
		Route::get('comments/active/list', 'CommentsController@getActiveComments')->name('get.active.comments');
		Route::get('comments/active/{id}', 'CommentsController@getActive')->name('comments.active');
		// Kampanya Yönetimi
		Route::get('campaigns', 'CampaignsController@getIndex')->name('get.campaigns');
		Route::get('campaigns/{id}/edit', 'CampaignsController@getUpdate')->name('get.campaigns.update');
		Route::put('campaigns/{id}/edit', 'CampaignsController@postUpdate')->name('post.campaigns.update');
		// İletişim Formu
		Route::get('contact-form', 'ContactController@getList')->name('get.contact-list');
		Route::post('contact-form/{id}', 'ContactController@getActive');
		Route::delete('contact-form/{id}', 'ContactController@destroy')->name('contact.destroy');
		// Admin Çıkış
		Route::get('logout', 'AuthController@getLogout')->name('get.logout');
	});

	Route::group([ 'middleware' => 'admin_guest' ], function(){
		Route::get('login', 'AuthController@getLogin')->name('admin.get.login');
		Route::post('login', 'AuthController@postLogin')->name('admin.post.login');
	});
});

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\City;

class UserController extends Controller
{

    protected $viewURL = '_admin.pages.users.';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = User::orderBy('id', 'DESC')->get();
        return view($this->viewURL.'list', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->viewURL.'create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = User::findOrFail($id);
        $cities = City::pluck('city', 'city');
        return view($this->viewURL.'update', compact('item', 'cities'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $item = User::findOrFail($id);
        $item->email = $request->email;
        $item->password = $request->password != null ? bcrypt($request->password) : $item->password;
        $item->name = $request->name;
        $item->lname = $request->lname;
        $item->phone = $request->phone;
        $item->city = $request->city;
        $item->active = $request->active;
        $item->save();

        return back()->with('message', 'Kullanıcı başarıyla düzenlendi');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        sleep(1);
        return back();
    }
}

app/Http/Controllers/User/AuthController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use App\Models\User;
use App\Models\City;
use Carbon\Carbon;
use Mail;
use Socialite;
use Illuminate\Support\Facades\Password;


class AuthController extends Controller
{
    protected $rules = [ 
            'name' => 'required|min:3|alpha_num',
            'lname' => 'required|min:3|alpha_num',
            'phone' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6',
            'confirm-password' => 'required|same:password',
            'date' => 'required',
            'city' => 'required',
         ];
	protected $registerURL  = '_user.auth.register';
	protected $loginURL 	= '_user.auth.login';
    protected $resetURL     = '_user.auth.password';

    // Kullanıcı giriş sayfası
    public function getLogin()
    {
    	return view($this->loginURL);
    }

    // Kullanıcı kayıt sayfası
    public function getRegister()
    {
        $cities = City::all();
    	return view($this->registerURL, compact('cities'));
    }

    // Kullanıcı Giriş İşlemleri
    public function postLogin(Request $request)
    {
        $infos = [ 'email' => $request->email, 'password' => $request->password ];
        if(Auth::attempt($infos))
        {
            if(Auth::user()->active == 0) {
                \Session::flash('loginMessage', 'E-mail adresi onaylanmamış');
                return back();
            }
            return redirect()->intended(route('user.dashboard'));
        }else{
            \Session::flash('loginMessage', 'E-mail veya Şifre Hatalı');
            return redirect()->back();
        }
    }

    // Kullanıcı kayıt işlemleri
    public function postRegister(Request $request)
    {
        $user = User::where('email', $request->email)->first();
        if($user){  
            $table = User::findOrFail($user->id);
            $table->password = bcrypt($request->password);
            $table->active = 1;
            $table->save();
        }else{
            $this->validate($request, $this->rules);
            $table = new User;
            $table->name = $request->name;
            $table->lname = $request->lname;
            $table->phone = $request->phone;
            $table->email = $request->email;
            $table->password = bcrypt($request->password);
            $table->date = Carbon::createFromFormat('d/m/Y', $request->date);
            $table->city = $request->city;
            $table->active = 1;
            $table->save();
        }
        
        Auth::loginUsingId($table->id);
        return redirect(route('user.dashboard'));
    }

    // Auth sonlandırma
    public function getLogout()
    {
        Auth::logout();
        return redirect(route('user.login'));
    }

    public function confirmation($token)
    {
        $user = User::where('activation_token', $token)->first();
        if(!is_null($user)){
            $user->active = 1;
            $user->activation_token = '';
            $user->save();
            return redirect(route('user.login'))->with('message', 'Üyelik işleminiz başarıyla gerçekleşti');
        }
    }

    public function getFacebookLogin()
    {
        return Socialite::driver('facebook')->redirect();
    }

    public function handleProviderCallback(Request $request)
    {
        $user = Socialite::driver('facebook')->user();
        $checkUser = User::where('email', $user->email)->first();
        $member = explode(' ', $user->name);
        if(!$checkUser){
            $table = new User;
            $table->name = $member[0];
            $table->lname = $member[1];
            $table->email = $user->email;
            $table->date = Carbon::now();
            $table->image = $user->avatar;
            $table->active = 1;
            $table->save();
            Auth::login($table);
            return redirect(route('user.dashboard'));
        }else{
            Auth::login($checkUser);
            return redirect(route('user.dashboard'));
        }

        // $user->token;
    }
}

app/Http/Controllers/User/CommentsController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use App\Models\Comment;

class CommentsController extends Controller
{
    protected $viewPath = '_user.pages.comments.index';

    public function getComments()
    {
    	$user = Auth::user()->load('comments.workshop');
		return view($this->viewPath, compact('user'));
    }

    public function commentDestroy($id)
    {
    	$item = Comment::where('id', $id)->delete();
    	return back();
    }
}

app/Http/Controllers/User/HomeController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\City;

class HomeController extends Controller
{
	protected $viewPath = '_user.pages.';

    public function getIndex()
    {
    	$cities = City::pluck('city', 'city');
    	return view($this->viewPath.'dashboard', compact('cities'));
    }
}

resources/views/_admin/pages/users/list.blade.php
@extends('_admin.master')
@section('content')
<div class="main-content">
    <div class="panel-content">
        <div class="row">
            <div class="col-md-12">
                <div class="widget">
                    <div class="table-area">
                        <div class="widget-title">
                            <h3>Kullanıcı Tablosu</h3>
                            <span>{{count($items)}} Kullanıcı Listelendi</span>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Ad Soyad</th>
                                        <th>E-mail</th>
                                        <th>Durum</th>
                                        <th>Oluşturulma Tarihi</th>
                                        <th>İşlemler</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @forelse($items as $item)
                                    <tr>
                                        <td>{{ $item->id }}</td>
                                        <td>{{ $item->name.' '.$item->lname }}</td>
                                        <td>{{ $item->email }}</td>
                                        <td>
                                        @if($item->active)
                                            <label class="label label-success">Aktif</label>
                                        @else
                                            <label class="label label-warning">Pasif</labe>
                                        @endif
                                        </td>
                                        <td>{{ $item->created_at->diffForHumans() }}</td>
                                        <td>
                                            <a href="{{route('users.edit', $item->id)}}">
                                                <button class="btn btn-edit">
                                                    Düzenle <i class="fa fa-edit"></i>
                                                </button>
                                            </a>
                                            {!! stuff_destroy([ 'users.destroy', $item->id]) !!}
                                        </td>
                                    </tr>
                                @empty
                                    <h3 class="text-center" style="color: #ff6b6b"> <i class="fa fa-exclamation" aria-hidden="true"></i> Kullanıcı Bulunamadı</h3>
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- Panel Content -->
</div><!-- Main Content -->
@endsection

resources/views/_admin/pages/users/update.blade.php
@extends('_admin.master')
@section('content')
<div class="main-content">
    <div class="panel-content">
        <div class="row">
            <div class="col-md-12">
                <div class="heading-sec">
                    <div class="row">
                        <div class="col-md-12">
                            @include('_admin.layouts.notifications')
                        </div>
                    </div>
                </div>
               <div class="widget">
                   <div class="form-elements-sec">
                        <div class="widget-title">
                            <h3>Kullanıcı Düzenle</h3>
                        </div>
                        {!! Form::open([ 'url' => route('users.update', $item->id), 'class' => 'sec', 'role' => 'form' ]) !!}
                        {{ method_field('PUT') }}
                            <div class="row">
                                <div class="col-md-6 m-b">
                                    <div class="form-group">
                                        <label>E-mail</label>
                                        <input type="text" placeholder="E-mail" class="form-control custom-input" name="email" id="email" value="{{ $item->email }}">
                                    </div>
                                </div>
                                <div class="col-md-6 m-b">
                                    <div class="form-group">
                                        <label>Şifre</label>
                                        <input type="password" placeholder="Şifre" class="form-control custom-input" name="password" id="password">
                                    </div>
                                </div>
                                <div class="col-md-6 m-b">
                                    <div class="form-group">
                                        <label>Ad</label>
                                        <input type="text" name="name" class="custom-input form-control" value="{{ $item->name }}">
                                    </div>
                                </div>
                                <div class="col-md-6 m-b">
                                    <div class="form-group">
                                        <label>Soyad</label>
                                        <input type="text" name="lname" class="custom-input form-control" value="{{ $item->lname }}">
                                    </div>
                                </div>
                                <div class="col-md-6 m-b">
                                    <div class="form-group">
                                        <label>Telefon</label>
                                        <input type="text" name="phone" class="custom-input form-control" value="{{ $item->phone }}">
                                    </div>
                                </div>
                                <div class="col-md-6 m-b">
                                    <div class="form-group">
                                        <label>Şehir</label>
                                        {!! Form::select('city', $cities, $item->city, [ 'class' => 'custom-input form-control' ]) !!}
                                    </div>
                                </div>
                                <div class="col-md-6 m-b">
                                    <div class="form-group">
                                        <label>Düğün Tarihi</label>
                                        <input type="text" value="{{ $item->date->format('d.m.Y') }}" class="form-control custom-input" name="date">
                                    </div>
                                </div>
                                <div class="col-md-6 m-b">
                                    <div class="form-group">
                                            <label>Durum</label>
                                            {!! Form::select('active',
                                                [ '1' => 'Aktif', '0' => 'Pasif' ],
                                                $item->active,
                                                ['class' => 'form-control custom-input']) !!}
                                    </div>
                                </div>
                                <hr>
                                <div class="col-md-12">
                                    <div class="record-buttons">
                                        <button class="btn btn-edit" type="submit">
                                            <i class="fa fa-edit"></i> Kullanıcı Düzenle 
                                        </button>
                                        <a href="{{ route('users.index') }}">
                                            <button class="btn btn-trash" type="button">
                                                <i class="fa fa-remove"></i> İptal
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {!! Form::close() !!}
                    </div>
               </div>
            </div>
        </div>
    </div><!-- Panel Content -->
</div><!-- Main Content -->
@endsection
@push('script')
<script>

</script>
@endpush 